export const PATHS = {
  HOME: "/",
  CARS: "/cars",
  ADD: "/add",
  LOGIN: "/login",
  CHAT_CLIENT: "/chat",
  SINGLE_AUTO: "/auto",
  CHATS_CLIENT: "/all_chats",
  ADMIN: "/admin",
  ADMIN_ADD_NEW_ADMIN: "/admin/add_new_admin",
  ADMIN_UPDATE_ADMINS: "/admin/update_admins",
  ADMIN_ADD_MARK: "/admin/add_mark",
  ADMIN_UPDATE_MARKS: "/admin/update_marks",
  ADMIN_ADD_MODELS: "/admin/add_model",
  ADMIN_UPDATE_MODELS: "/admin/update_models",
  ADMIN_ADD_GENERATION: "/admin/add_generation",
  ADMIN_UPDATE_GENERATION: "/admin/update_generations",
  ADMIN_ADD_OTHER_CATEGORIES: "/admin/add_other_categories",
};
